Scrape started on: 01:03:47
[STARTUP | Thu Jul  1 01:03:47 2021 | main.py | <module>]: Init Database
[STARTUP | Thu Jul  1 01:03:47 2021 | main.py | <module>]: Running Controlled Chome to get TokenFomo.io full list
[STARTUP | Thu Jul  1 01:03:47 2021 | main.py | <module>]: Selinum Scrape Done Closing
[STARTUP | Thu Jul  1 01:03:47 2021 | main.py | <module>]: Parse the Fomo HTML
[STARTUP | Thu Jul  1 01:03:47 2021 | main.py | <module>]: Beginning Coin Loop
[SCRAPE | Thu Jul  1 01:03:47 2021 | /home/fullsend/cryptovesting/pyFiles/scrape_poc.py | getSniffer]: No Sim tokens for token: TEST COIN
[DEBUG | Thu Jul  1 01:03:48 2021 | /home/fullsend/cryptovesting/pyFiles/sql_connector.py | addTokensPostSniff]: insert into tokens_post_sniff (token_uuid) values ("50293e9b852f4772a6741a0de92d4cdc")
[SEVERE | Thu Jul  1 01:03:48 2021 | /home/fullsend/cryptovesting/pyFiles/cglobals.py | getException]: *** print_tb:
  File "/home/fullsend/cryptovesting/pyFiles/sql_connector.py", line 134, in addTokensPostSniff
    cursor.execute(insQuery)
[SEVERE | Thu Jul  1 01:03:48 2021 | /home/fullsend/cryptovesting/pyFiles/cglobals.py | getException]: *** print_exception:
Traceback (most recent call last):
  File "/home/fullsend/cryptovesting/pyFiles/sql_connector.py", line 134, in addTokensPostSniff
    cursor.execute(insQuery)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'token_uuid' at row 1
[COMPLETED | Thu Jul  1 01:03:48 2021 | main.py | <module>]: {'addTokens': 1, 'addTokensPostSniff': 1, 'addSimilarToken': 0}
